[build-system]
requires = ["hatchling>=1.27.0", "babel>=2.17.0"]
build-backend = "hatchling.build"

[project]
name = "udt"
version = "0.1.0"
description = "Adventure to new framework!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pip",
    "ipykernel",
    "pandas-stubs",
    "vnpy",
    "vnpy-akshare",
    "vnpy-ctp",
    "vnpy-ctptest",
    "vnpy-mysql",
    # "vnpy-portfoliostrategy",
    "vnpy-rpcservice",
    "vnpy-simplestrategy",
    # "vnpy-sopt",  # C++ 编译暂时有问题
    # "vnpy-sopttest",  # 同上
    "vnpy-sqlite",
    "vnpy-tts",
    "vnpy-tushare",
]

[tool.uv.sources]
vnpy = { path = "../vnpy" }
vnpy-akshare = { path = "../vnpy_akshare" }
vnpy-ctp = { path = "../vnpy_ctp" }
vnpy-ctptest = { path = "../vnpy_ctptest" }
vnpy-datamanager = { path = "../vnpy_datamanager" }
vnpy-mysql = { path = "../vnpy_mysql" }
# vnpy-portfoliostrategy = { path = "../vnpy_portfoliostrategy" }
vnpy-rpcservice = { path = "../vnpy_rpcservice" }
vnpy-simplestrategy = { path = "../vnpy_simplestrategy" }
vnpy-sopt = { path = "../vnpy_sopt" }
vnpy-sopttest = { path = "../vnpy_sopttest" }
vnpy-sqlite = { path = "../vnpy_sqlite" }
vnpy-tts = { path = "../vnpy_tts" }
vnpy-tushare = { path = "../vnpy_tushare" }

[tool.ruff]
target-version = "py313"
output-format = "full"

[tool.ruff.lint]
select = [
    "B",  # flake8-bugbear
    "E",  # pycodestyle error
    "F",  # pyflakes
    "UP",  # pyupgrade
    "W",  # pycodestyle warning
]
ignore = ["E501"]

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
